### ISSUE TITLE
Options menu shows an empty screen

### ISSUE THREAD

**Issue by lazaromenezes** [DOGamedev5/Recompose_World-of-Art#70]
When you click the Options menu, it shows an empty screen and nothing else

![image](https://github.com/user-attachments/assets/58acfa65-d01c-408a-9281-d2cf2a3d6d15)

**Comment by DOGamedev5** [comment]
esse é o problema do options se esticar que tanto me atormenta...

**Comment by DOGamedev5** [comment]
there is what happens
![image](https://github.com/user-attachments/assets/d03b1239-ff90-4213-a70d-80b82f39042d)
