### ISSUE TITLE
The lights menu seems to be reversed

### ISSUE THREAD

**Issue by lazaromenezes** [DOGamedev5/Recompose_World-of-Art#74]
The "Simple Lights" option seems to be reversed: When off, lights are on, when on, lights are off. See the video

https://github.com/user-attachments/assets/fb084e26-5d73-4c0b-9949-a3168750948f

**Comment by DOGamedev5** [comment]
o nome "luzes simples" é basicamente oq diz, serve para deixar o jogo mais leve, quanto q quanto se desativa, seria como se usasse luzes mais detalhadas q consome mais processamento da gpu

**Comment by lazaromenezes** [comment]
Mudar o texto para "Usar luzes simples" ficaria melhor, na minha opinião, e talvez um tooltip mostrando os detalhes do que isso faz, assim não confunde quem estiver usando.
