### ISSUE TITLE
Consegui ficar em pé no meio da parede

### ISSUE THREAD

**Issue by lazaromenezes** [DOGamedev5/Recompose_World-of-Art#76]
https://github.com/user-attachments/assets/b2eec530-f983-4d54-9199-615b482a586e

Acho que tem a ver com agaixar e logo em seguida apertar o botão de correr

**Comment by DOGamedev5** [comment]
misericordia achava q tinha ressolvido essa bomba ai

**Comment by DOGamedev5** [comment]
qual foi os botões precionados?

**Comment by lazaromenezes** [comment]
Se não me engano vc abaixa, começa a andar e aperta o "L" no meio da caminhada, ele sobe no estado de corrida e passa no meio da parede
